Creating a dummy data of 34 data items or more
explore the data: type. shape, mathematical operations
Convert your dummy data into an array.
type. shape, mathematical operation

In [11]:
data=[52,99, 53, 64, 10, 87, 33, 5, 77, 35, 27, 84, 17, 9, 39, 44, 26, 70, 40, 11, 68, 60, 59, 41, 52, 50, 23, 56, 78, 1, 4, 36, 8, 30, 46, 74]

In [15]:
type(data)

list

In [18]:
print(type(data))

<class 'list'>


In [20]:
data.shape()

AttributeError: 'list' object has no attribute 'shape'

In [54]:
data+2

TypeError: can only concatenate list (not "int") to list

In [48]:
data*2

[52,
 99,
 53,
 64,
 10,
 87,
 33,
 5,
 77,
 35,
 27,
 84,
 17,
 9,
 39,
 44,
 26,
 70,
 40,
 11,
 68,
 60,
 59,
 41,
 52,
 50,
 23,
 56,
 78,
 1,
 4,
 36,
 8,
 30,
 46,
 74,
 52,
 99,
 53,
 64,
 10,
 87,
 33,
 5,
 77,
 35,
 27,
 84,
 17,
 9,
 39,
 44,
 26,
 70,
 40,
 11,
 68,
 60,
 59,
 41,
 52,
 50,
 23,
 56,
 78,
 1,
 4,
 36,
 8,
 30,
 46,
 74]

In [26]:
import numpy as np

In [50]:
grades=np.array(data)

In [52]:
grades

array([52, 99, 53, 64, 10, 87, 33,  5, 77, 35, 27, 84, 17,  9, 39, 44, 26,
       70, 40, 11, 68, 60, 59, 41, 52, 50, 23, 56, 78,  1,  4, 36,  8, 30,
       46, 74])

In [32]:
type(grades)

numpy.ndarray

In [34]:
print(type(grades))

<class 'numpy.ndarray'>


In [42]:
grades.shape

(36,)

In [44]:
grades*2

array([104, 198, 106, 128,  20, 174,  66,  10, 154,  70,  54, 168,  34,
        18,  78,  88,  52, 140,  80,  22, 136, 120, 118,  82, 104, 100,
        46, 112, 156,   2,   8,  72,  16,  60,  92, 148])

In [46]:
grades+2

array([ 54, 101,  55,  66,  12,  89,  35,   7,  79,  37,  29,  86,  19,
        11,  41,  46,  28,  72,  42,  13,  70,  62,  61,  43,  54,  52,
        25,  58,  80,   3,   6,  38,  10,  32,  48,  76])

In [56]:
grades.mean()

43.55555555555556

random number egenrator
 
normal disticbuted or unofrm distributed data
 
rand, randn and randi numbers
 
rand()
randn()
randi()
 

In [63]:
study_hours = [4.5,3.5, 15.8, 7.2, 22.1, 35.4, 9.6, 50.7, 60.3, 73.9, 82.2, 
    100.1, 45.0, 12.3, 18.5, 51.2, 67.4, 24.8, 88.9, 44.7, 99.6,
    20.4, 71.1, 29.3, 10.0, 27.2, 36.5, 17.9, 39.8, 41.0, 80.4,
    55.6, 62.7, 30.3, 90.2, 33.9
]

In [65]:
type(study_hours)

list

In [69]:
student_data= np.array([study_hours,grades])

In [71]:
student_data

array([[  4.5,   3.5,  15.8,   7.2,  22.1,  35.4,   9.6,  50.7,  60.3,
         73.9,  82.2, 100.1,  45. ,  12.3,  18.5,  51.2,  67.4,  24.8,
         88.9,  44.7,  99.6,  20.4,  71.1,  29.3,  10. ,  27.2,  36.5,
         17.9,  39.8,  41. ,  80.4,  55.6,  62.7,  30.3,  90.2,  33.9],
       [ 52. ,  99. ,  53. ,  64. ,  10. ,  87. ,  33. ,   5. ,  77. ,
         35. ,  27. ,  84. ,  17. ,   9. ,  39. ,  44. ,  26. ,  70. ,
         40. ,  11. ,  68. ,  60. ,  59. ,  41. ,  52. ,  50. ,  23. ,
         56. ,  78. ,   1. ,   4. ,  36. ,   8. ,  30. ,  46. ,  74. ]])

In [75]:
type(student_data)

numpy.ndarray

In [82]:
student_data[1][2:20]

array([53., 64., 10., 87., 33.,  5., 77., 35., 27., 84., 17.,  9., 39.,
       44., 26., 70., 40., 11.])

In [102]:
avg_hours = student_data[0].mean()
avg_grades= student_data[1].mean()

print('Average study hours:', avg_hours,'\nAverage study hours:' ,avg_grades)



Average study hours: 43.44444444444445 
Average study hours: 43.55555555555556


In [112]:
import pandas as pd



In [118]:
type(student_data)

numpy.ndarray

In [120]:
student_data.shape

(2, 36)

In [146]:

students_details =pd.DataFrame({"Names": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Isaac", "Jack","Kathy", "Leo", "Mona", "Nathan", "Olivia", "Paul", "Quincy", "Rachel", "Sam", "Tina",
    "Uma", "Vera", "Walter", "Xander", "Zane", "Ava", "Blake", "Cathy", "Derek", "Emma",    "Felix", "Gina", "Holly", "Ivy", "James", "Kelly"],
                               "study_hour":student_data[0], "Grades":student_data[1]})
                  

In [136]:
students_details

Names  study_hour  Grades
0     Alice         4.5    52.0
1       Bob         3.5    99.0
2   Charlie        15.8    53.0
3     David         7.2    64.0
4       Eve        22.1    10.0
5     Frank        35.4    87.0
6     Grace         9.6    33.0
7    Hannah        50.7     5.0
8     Isaac        60.3    77.0
9      Jack        73.9    35.0
10    Kathy        82.2    27.0
11      Leo       100.1    84.0
12     Mona        45.0    17.0
13   Nathan        12.3     9.0
14   Olivia        18.5    39.0
15     Paul        51.2    44.0
16   Quincy        67.4    26.0
17   Rachel        24.8    70.0
18      Sam        88.9    40.0
19     Tina        44.7    11.0
20      Uma        99.6    68.0
21     Vera        20.4    60.0
22   Walter        71.1    59.0
23   Xander        29.3    41.0
24     Zane        10.0    52.0
25      Ava        27.2    50.0
26    Blake        36.5    23.0
27    Cathy        17.9    56.0
28    Derek        39.8    78.0
29     Emma        41.0     1.0
30    Felix        80.4     4.0
31     Gina        55.6    36.0
32    Holly        62.7     8.0
33      Ivy        30.3    30.0
34    James        90.2    46.0
35    Kelly        33.9    74.0

In [148]:
sample_list=[1,2,3,4,5,6,7,8,9,10]
type(sample_list)

list

In [156]:
sample_array=np.array(sample_list)
sample_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
print(type(sample_array))

<class 'numpy.ndarray'>


In [166]:
matrix = sample_array.reshape(2, 5)

In [168]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [181]:
first_row=matrix[0]
first_row

array([1, 2, 3, 4, 5])

In [187]:
second_column=matrix[:,1]
second_column

array([2, 7])

In [189]:
#Compute the mean, sum, and standard deviation of all elements in the matrix

In [196]:
mean_matrix=np.mean(matrix)

In [198]:
mean_matrix

5.5

In [200]:
sum_matrix=np.sum(matrix)
sum_matrix

55

In [202]:
sd_matrix=np.std(matrix)
sd_matrix

2.8722813232690143

In [208]:
Dataframe_1=pd.DataFrame({"Name":["Alice","Bob","Carol","Dave"],
"Age":[20,22,19,21],"Gender":["F","M","F","M"],	
"City":["New York","Boston","Chicago","Seattle"],"Marks":[85,90,78,88]})
	


In [210]:
Dataframe_1


Name  Age Gender      City  Marks
0  Alice   20      F  New York     85
1    Bob   22      M    Boston     90
2  Carol   19      F   Chicago     78
3   Dave   21      M   Seattle     88