Creating a dummy data of 34 data items or more
explore the data: type. shape, mathematical operations
Convert your dummy data into an array.
type. shape, mathematical operation

In [5]:
data=[52,99, 53, 64, 10, 87, 33, 5, 77, 35, 27, 84, 17, 9, 39, 44, 26, 70, 40, 11, 68, 60, 59, 41, 52, 50, 23, 56, 78, 1, 4, 36, 8, 30, 46, 74]

In [7]:
type(data)

list

In [9]:
print(type(data))

<class 'list'>


In [15]:
data*2

[52,
 99,
 53,
 64,
 10,
 87,
 33,
 5,
 77,
 35,
 27,
 84,
 17,
 9,
 39,
 44,
 26,
 70,
 40,
 11,
 68,
 60,
 59,
 41,
 52,
 50,
 23,
 56,
 78,
 1,
 4,
 36,
 8,
 30,
 46,
 74,
 52,
 99,
 53,
 64,
 10,
 87,
 33,
 5,
 77,
 35,
 27,
 84,
 17,
 9,
 39,
 44,
 26,
 70,
 40,
 11,
 68,
 60,
 59,
 41,
 52,
 50,
 23,
 56,
 78,
 1,
 4,
 36,
 8,
 30,
 46,
 74]

In [17]:
import numpy as np

In [19]:
grades=np.array(data)

In [21]:
grades

array([52, 99, 53, 64, 10, 87, 33,  5, 77, 35, 27, 84, 17,  9, 39, 44, 26,
       70, 40, 11, 68, 60, 59, 41, 52, 50, 23, 56, 78,  1,  4, 36,  8, 30,
       46, 74])

In [23]:
type(grades)

numpy.ndarray

In [25]:
print(type(grades))

<class 'numpy.ndarray'>


In [27]:
grades.shape

(36,)

In [29]:
grades*2

array([104, 198, 106, 128,  20, 174,  66,  10, 154,  70,  54, 168,  34,
        18,  78,  88,  52, 140,  80,  22, 136, 120, 118,  82, 104, 100,
        46, 112, 156,   2,   8,  72,  16,  60,  92, 148])

In [31]:
grades+2

array([ 54, 101,  55,  66,  12,  89,  35,   7,  79,  37,  29,  86,  19,
        11,  41,  46,  28,  72,  42,  13,  70,  62,  61,  43,  54,  52,
        25,  58,  80,   3,   6,  38,  10,  32,  48,  76])

In [33]:
grades.mean()

43.55555555555556

random number egenrator
 
normal disticbuted or unofrm distributed data
 
rand, randn and randi numbers
 
rand()
randn()
randi()
 

In [38]:
study_hours = [4.5,3.5, 15.8, 7.2, 22.1, 35.4, 9.6, 50.7, 60.3, 73.9, 82.2, 
    100.1, 45.0, 12.3, 18.5, 51.2, 67.4, 24.8, 88.9, 44.7, 99.6,
    20.4, 71.1, 29.3, 10.0, 27.2, 36.5, 17.9, 39.8, 41.0, 80.4,
    55.6, 62.7, 30.3, 90.2, 33.9
]

In [40]:
type(study_hours)

list

In [42]:
student_data= np.array([study_hours,grades])

In [44]:
student_data

array([[  4.5,   3.5,  15.8,   7.2,  22.1,  35.4,   9.6,  50.7,  60.3,
         73.9,  82.2, 100.1,  45. ,  12.3,  18.5,  51.2,  67.4,  24.8,
         88.9,  44.7,  99.6,  20.4,  71.1,  29.3,  10. ,  27.2,  36.5,
         17.9,  39.8,  41. ,  80.4,  55.6,  62.7,  30.3,  90.2,  33.9],
       [ 52. ,  99. ,  53. ,  64. ,  10. ,  87. ,  33. ,   5. ,  77. ,
         35. ,  27. ,  84. ,  17. ,   9. ,  39. ,  44. ,  26. ,  70. ,
         40. ,  11. ,  68. ,  60. ,  59. ,  41. ,  52. ,  50. ,  23. ,
         56. ,  78. ,   1. ,   4. ,  36. ,   8. ,  30. ,  46. ,  74. ]])

In [52]:
import pandas as pd



In [58]:

students_details =pd.DataFrame({"Names": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Isaac", "Jack","Kathy", "Leo", "Mona", "Nathan", "Olivia", "Paul", "Quincy", "Rachel", "Sam", "Tina",
    "Uma", "Vera", "Walter", "Xander", "Zane", "Ava", "Blake", "Cathy", "Derek", "Emma",    "Felix", "Gina", "Holly", "Ivy", "James", "Kelly"],
                               "study_hour":student_data[0], "Grades":student_data[1]})
                  

In [136]:
students_details

Names  study_hour  Grades
0     Alice         4.5    52.0
1       Bob         3.5    99.0
2   Charlie        15.8    53.0
3     David         7.2    64.0
4       Eve        22.1    10.0
5     Frank        35.4    87.0
6     Grace         9.6    33.0
7    Hannah        50.7     5.0
8     Isaac        60.3    77.0
9      Jack        73.9    35.0
10    Kathy        82.2    27.0
11      Leo       100.1    84.0
12     Mona        45.0    17.0
13   Nathan        12.3     9.0
14   Olivia        18.5    39.0
15     Paul        51.2    44.0
16   Quincy        67.4    26.0
17   Rachel        24.8    70.0
18      Sam        88.9    40.0
19     Tina        44.7    11.0
20      Uma        99.6    68.0
21     Vera        20.4    60.0
22   Walter        71.1    59.0
23   Xander        29.3    41.0
24     Zane        10.0    52.0
25      Ava        27.2    50.0
26    Blake        36.5    23.0
27    Cathy        17.9    56.0
28    Derek        39.8    78.0
29     Emma        41.0     1.0
30    Felix        80.4     4.0
31     Gina        55.6    36.0
32    Holly        62.7     8.0
33      Ivy        30.3    30.0
34    James        90.2    46.0
35    Kelly        33.9    74.0

In [ ]:
Day 2
Implement the following:- 
 loc, 
iloc, 
explicit method of filtering
Implicit method filtering
Query method


In [60]:
students_details.loc[0:6]

Names  study_hour  Grades
0    Alice         4.5    52.0
1      Bob         3.5    99.0
2  Charlie        15.8    53.0
3    David         7.2    64.0
4      Eve        22.1    10.0
5    Frank        35.4    87.0
6    Grace         9.6    33.0

In [62]:
students_details.iloc[0:6]

Names  study_hour  Grades
0    Alice         4.5    52.0
1      Bob         3.5    99.0
2  Charlie        15.8    53.0
3    David         7.2    64.0
4      Eve        22.1    10.0
5    Frank        35.4    87.0

In [68]:
students_details.iloc[0:6,[1,2]]# slicing can be done by iloc function

study_hour  Grades
0         4.5    52.0
1         3.5    99.0
2        15.8    53.0
3         7.2    64.0
4        22.1    10.0
5        35.4    87.0

In [76]:
#explicit method of filtering
students_details.loc[students_details["study_hour"]>90]

Names  study_hour  Grades
11    Leo       100.1    84.0
20    Uma        99.6    68.0
34  James        90.2    46.0

In [82]:
students_details.loc[students_details["Names"]=="Emma"]

Names  study_hour  Grades
29  Emma        41.0     1.0

In [84]:
#Implicit method filtering
students_details[students_details["Names"]=="Emma"]

Names  study_hour  Grades
29  Emma        41.0     1.0

In [88]:
students_details.loc[students_details["Grades"]>80]

Names  study_hour  Grades
1     Bob         3.5    99.0
5   Frank        35.4    87.0
11    Leo       100.1    84.0